### PR TITLE
User/jpk/python3 conversion

### PR DESCRIPTION
**Pull request by jkrasting**
Completed conversion of script to be compatible with both Python 2.x and 3.x.

### CODE REVIEW

**Comment by jkrasting** [comment]
@adcroft -- just a gentle nudge on this PR

**Comment by adcroft** [comment]
This isn't working with python3 for me:
```
../MOM6param_scan.py MOM_parameter_doc.all | sed 's/ $//' > test1.json
Traceback (most recent call last):
  File "../MOM6param_scan.py", line 343, in <module>
    if __name__ == '__main__': parseCommandLine()
  File "../MOM6param_scan.py", line 66, in parseCommandLine
    main(args)
  File "../MOM6param_scan.py", line 83, in main
    else: P[file] = Parameters(file, exclude=args.exclude)
  File "../MOM6param_scan.py", line 182, in __init__
    open_file = open_file.read().decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by jkrasting** [comment]
What version of Python are you using?

**Comment by adcroft** [comment]
3.6

**Comment by jkrasting** [comment]
Try this new commit:  88abe44

**Comment by adcroft** [comment]
Looks good now:
image

**Pull request merged**
